# Configuration file for YREC test suite

[paths]

# Location of YREC executable to test
yrec = ../src/yrec

# Test input locations
# Entries in this list may be directories where nml1,nml2 pairs are found.
# All corresponding nml1,nml2 pairs will be collected as test cases and
# run.
#
# A comma-separated list of
#   directory, nm1-file, nml2-file
# may also be used to define a single test case.
tests = .

# Subdirectory of each test directory which will hold test reference outputs
# used for comparison of future runs.
reference_dir = standard

[options]
show_output_upon_failure = True

[tolerances]
float_frac_tol = 0.02
int_abs_tol    = 0
